find/urls.py
from django.urls import path

from . import views

app_name = 'find'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:user>/', views.view_send_request, name='view_send_request'),
    path('<str:user>/requestSent', views.send_buddy_request, name='view_buddy_request'),
]

login/urls.py
from django.urls import path, include

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.login, name='login'),
    path('home', views.home, name='home')
]

userAccount/urls.py
from django.urls import path, include

from . import views

app_name = 'userAccount'
urlpatterns = [
    path('', views.view_account, name='view_account'),
    path('find/',views.has_account, name='has_account'),
    path('save/',views.save, name='save'),
    # path('course/', views.course_form, name='course_form'),
    # path('add/', views.add_course, name='add_course'),
    # path('delete/', views.delete_course, name='delete_course'),
    path('find/availability/', views.has_availability, name='has_availability'),
    path('availability/', views.view_availability, name="view_availability"),
    path('availability/save', views.save_availability, name="save_availability"),
    path('buddies/', views.view_buddies, name='view_buddies'),
    path('buddies/<str:buddy_name>/', views.buddy_select, name='buddy_select'),
    path('approve/', views.approve_buddy, name='approve_buddy'),
    path('deny/', views.deny_buddy, name='deny_buddy'),
    path('contact/', views.contact_info, name='contact_info'),
    path('contact/save', views.save_contact, name='save_contact'),
    path('zoom', views.zoom, name='zoom'),
    path('convo/<str:buddy_name>/<str:read_mode>', views.get_conversation, name='get_convo'),
    path('message/', views.new_message, name='new_msg'),
    path('removezoom/', views.remove_zoom, name='removezoom')
]

virtualstudybuddy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('login.urls')),
    path('find/', include('find.urls')),
    path('buddies/', include('buddies.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('userAccount.urls', namespace='userAccount')),
]

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from userAccount.models import userAccount


def login(request):
    template = loader.get_template('login/login.html')
    context = {}
    return HttpResponse(template.render(context, request))

def home(request):
    template = loader.get_template('login/home.html')
    if (userAccount.objects.filter(user=request.user).count() > 0):
        has_profile = True
    else:
        has_profile = False

    context = {
        'hasProfile': has_profile
    }
    return HttpResponse(template.render(context, request))

login/templates/login/base.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<style>
  .footer {
    padding-top: 20px;
    padding-bottom: 20px;
    color: white;
  }

  .user-icon {
    height: 35px;
    cursor: pointer;
  }
</style>
<html>
  <head>
    <title>
      Virtual Study Buddy
    </title>
  </head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% if user.is_authenticated %}
  <link rel="stylesheet" type="text/css" href="{% static 'login/fonts.css' %}" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/home">Virtual Study Buddy</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'find:index' %}">Explore <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'userAccount:view_buddies' %}">My Buddies</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'userAccount:has_account' %}">Profile</a>
          </li>
        </ul>
      </div>
      <div class="dropdown">
        <a class="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img class="user-icon" src="{% static 'accounts/images/user-icon.png' %}">
        </a>
      
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
          <a href="{% url 'account_logout' %}" class="dropdown-item" href="#">Log Out</a>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <!-- <footer class="page-footer fixed-bottom font-small bg-secondary footer">
      <div class="container-fluid text-center">
        <div class="row">
          <div class="col-md-6 mt-md-0 mt-3">
            <h5 class="text-uppercase font-weight-bold">Links</h5>
            <p>...</p>
          </div>
          <hr class="clearfix w-100 d-md-none pb-3">
          <div class="col-md-6 mb-md-0 mb-3">
            <h5 class="text-uppercase font-weight-bold">Author</h5>
            <p>#TeamFireFlyGang</p>
          </div>
        </div>
      </div>
      <div class="footer-copyright text-center py-3">© 2020 Copyright FireFly Inc.
      </div>
    </div> -->
    {% else %}
    <meta http-equiv="refresh" content="0.1; URL='{% url 'login:login' %}'" />
    {% endif %}
  </html>

login/templates/login/home.html
{% extends "login/base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'login/home.css' %}">
  
<div class="root-container">
  <span class="study-together">
    Let's study together.
  </span>
  <div class="homepage-card">
    {% if hasProfile == False %}
      <span class="homepage-card-body">First, why don't you tell us a bit about yourself?</span>
      <a href="{% url 'userAccount:has_account' %}">
        <button type="button" class="btn btn-primary btn-lg profile-button">
          Create A Profile
        </button>
      </a>
    {% else %}
      <span class="homepage-card-body">Are you ready to meet your new study buddies?</span>
      <a href="{% url 'find:index' %}">
        <button type="button" class="btn btn-primary btn-lg profile-button">
          Explore
        </button>
      </a>
    {% endif %}
  </div>
</div>
{% endblock %}

login/templates/login/login.html
{% load static %}
{% load socialaccount %}
<style>
  .footer {
    padding-top: 20px;
    padding-bottom: 20px;
    color: white;
  }
  </style>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'login/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/fonts.css' %}" />
    <title>Login</title>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand">Virtual Study Buddy</a>
    </nav>
    <br>

    <div class=login-container>

      {% if user.is_authenticated %}
      <meta http-equiv="refresh" content="0.01; URL='{% url 'login:home' %}'" />
      {% else %}
      <div class="root-container">
        <div class="text-wrapper">
          <span class="login-main-text welcome">
            Welcome
          </span>
          <span class="login-main-text welcome-body">
            To Your New Favorite
          </span>
          <span class="login-main-text welcome-body">
            Study Space
          </span>
          <div class="button-container">
            <a href="{% provider_login_url 'google' %}">
              <button type="button" class="btn btn-primary btn-lg sign-in-button">
                Sign In With Google
              </button>
            </a>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </body>
</html>