find/urls.py
from django.urls import path

from . import views

app_name = 'find'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:user>/', views.view_send_request, name='view_send_request'),
    path('<str:user>/requestSent', views.send_buddy_request, name='view_buddy_request'),
]

userAccount/urls.py
from django.urls import path, include

from . import views

app_name = 'userAccount'
urlpatterns = [
    path('', views.view_account, name='view_account'),
    path('find/',views.has_account, name='has_account'),
    path('save/',views.save, name='save'),
    # path('course/', views.course_form, name='course_form'),
    # path('add/', views.add_course, name='add_course'),
    # path('delete/', views.delete_course, name='delete_course'),
    path('find/availability/', views.has_availability, name='has_availability'),
    path('availability/', views.view_availability, name="view_availability"),
    path('availability/save', views.save_availability, name="save_availability"),
    path('buddies/', views.view_buddies, name='view_buddies'),
    path('buddies/<str:buddy_name>/', views.buddy_select, name='buddy_select'),
    path('approve/', views.approve_buddy, name='approve_buddy'),
    path('deny/', views.deny_buddy, name='deny_buddy'),
    path('contact/', views.contact_info, name='contact_info'),
    path('contact/save', views.save_contact, name='save_contact'),
    path('zoom', views.zoom, name='zoom'),
    path('convo/<str:buddy_name>/<str:read_mode>', views.get_conversation, name='get_convo'),
    path('message/', views.new_message, name='new_msg'),
    path('removezoom/', views.remove_zoom, name='removezoom')
]

virtualstudybuddy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('login.urls')),
    path('find/', include('find.urls')),
    path('buddies/', include('buddies.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('userAccount.urls', namespace='userAccount')),
]

userAccount/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
import datetime

# Create your models here.
class userAccount(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    major = models.CharField(max_length=50)
    bio = models.TextField()
    computing_id = models.CharField(max_length=7)
    phone_number = models.CharField(max_length=15)
    discord_name = models.CharField(max_length=50)
    def __str__(self):
        return self.first_name + " " + self.last_name

    def getCourses(self):
        return self.courses.all()

    def getBuddies(self):
        requested = self.requester.all()
        requestee = self.requestee.all()
        accepted = []
        pendingYourApproval = []
        pendingTheirApproval = []
        denied = []
        for buddy in requested:
            if buddy.approved:
                accepted.append(buddy.requestee)
            elif buddy.denied:
                denied.append(buddy.requestee)
            else:
                pendingTheirApproval.append(buddy.requestee)
        for buddy in requestee:
            if buddy.approved:
                accepted.append(buddy.requester)
            elif buddy.denied:
                denied.append(buddy.requester)
            else:
                pendingYourApproval.append(buddy.requester)
        return {"accepted" : accepted, "pendingYourApproval" : pendingYourApproval, "pendingTheirApproval" : pendingTheirApproval, "denied" : denied}
        
    def getSharedCourses(self, user2):
        self_courses = self.courses.all()
        user2_courses = user2.courses.all()
        shared = [course for course in self_courses if course in user2_courses] 
        return shared
    def getBuddyObject(self, buddy_object):
        requested = self.requester.all()
        for buddy in requested:
            if (buddy.requestee==buddy_object and buddy.approved):
                return buddy
        requester = self.requestee.all()
        for buddy in requester:
            if (buddy.requester==buddy_object and buddy.approved):
                return buddy
        return None
    def getUpcomingMeetings(self, buddy_object):
        buddy = self.getBuddyObject(buddy_object)
        if (not buddy):
            return None
        meetings = buddy.buddies.all()
        for meeting in meetings:
            date_time = meeting.start_time.split(" ")
            date = date_time[0].split("-")
            time = date_time[1].split(":")
            start = datetime.datetime(int(date[0]), int(date[1]), int(date[2]), int(time[0]), int(time[1]), int(time[2]))
            if (datetime.datetime.now()-datetime.timedelta(hours=1) < start):
                return meeting
            else:
                meeting.delete()
        return None

class Course(models.Model):
    student = models.ForeignKey(userAccount, related_name='courses', on_delete=models.CASCADE)
    mnemonic = models.CharField(max_length=4)
    number = models.CharField(max_length=4)
    def __str__(self):
        return self.mnemonic + self.number + " for " + str(self.student)
    def __eq__(self, other):
        if isinstance(other, Course):
            return (self.number == other.number and self.mnemonic == other.mnemonic)
        return False
    def __hash__(self):
        return super().__hash__()

class Availability(models.Model):
    student = models.ForeignKey(userAccount, related_name='availability', on_delete=models.CASCADE, unique=True)
    calendar = models.CharField(max_length=112)

class buddies(models.Model):
    requester = models.ForeignKey(userAccount, related_name='requester', on_delete=models.CASCADE)
    requestee = models.ForeignKey(userAccount, related_name='requestee', on_delete=models.CASCADE)
    request_message = models.TextField()
    approved = models.BooleanField()
    denied_message = models.TextField()
    denied = models.BooleanField()

class ZoomMeeting(models.Model):
    buddies = models.ForeignKey(buddies, related_name='buddies', on_delete=models.CASCADE)
    meeting_link = models.TextField()
    start_time = models.TextField()

class Message(models.Model):
    unread = models.BooleanField()
    content = models.CharField(max_length=10000)
    sequence = models.IntegerField()
    from_requester = models.BooleanField()
    buddies = models.ForeignKey(buddies, on_delete=models.CASCADE)

userAccount/forms.py
from django import forms
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker

class MyForm(forms.Form):
    datetime_field = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

userAccount/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import userAccount, Course, Availability, buddies, Message, ZoomMeeting
from django.template import loader
from django.contrib import messages
from django.contrib.auth.models import User
from .const_data import major_options, course_data, dummy_convo
import random
import json
import requests
from zoomus import ZoomClient
import datetime
from .forms import MyForm


# Create your views here.

def has_availability(request):
    if (request.user.is_authenticated):
        if (userAccount.objects.filter(user=request.user).count() > 0):
            return HttpResponseRedirect(reverse('userAccount:view_availability'))
        else:
            user = request.user
            new_account = userAccount(user=user, first_name="", last_name="")
            new_account.save()
            return HttpResponseRedirect(reverse('userAccount:view_availability'))
    else:
        messages.add_message(request, messages.ERROR, "Login before attempting to view availability")
        return HttpResponseRedirect(reverse('login:login'))

def view_availability(request):
    if (request.user.is_authenticated):
        currentUser = userAccount.objects.get(user=request.user)
        availability = currentUser.availability.all()
        calendar = ""
        if availability.count() > 0:
            calendar = availability[0].calendar

        template = loader.get_template('userAccount/availabilityForm.html')
        days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
        times = []
        for i in range(8, 12):
            times.append(str(i) + ":00 AM")
        times.append("12:00 PM")
        for i in range(1,12):
            times.append(str(i) + ":00 PM")

        context = {
            'range16': range(16),
            'range7': range(7),
            'days': days,
            'times': times,
            'calendar': calendar
            }
        return HttpResponse(template.render(context, request))
    else:
        messages.add_message(request, messages.ERROR, "Login before attempting to view availability")
        return HttpResponseRedirect(reverse('login:login'))

def save_availability(request):
    try:
        student = userAccount.objects.get(user=request.user)
        old_availability = student.availability.all()
        if old_availability.count() > 0:
            old_availability[0].delete()
            
        calendar = request.POST.get("calendar")

        availability = Availability(student=student, calendar=calendar)
        availability.save()
        messages.add_message(request, messages.SUCCESS, "Account information successfully updated")
        return HttpResponseRedirect(reverse('userAccount:view_availability'))
    except:
        if(request.user.is_authenticated):
            messages.add_message(request, messages.ERROR, "Error updating account information")
            return HttpResponseRedirect(reverse('userAccount:view_account'))
        else:
            messages.add_message(request, messages.ERROR, "Login before attempting to view account")
            return HttpResponseRedirect(reverse('login:login'))
    
def has_account(request):
    if(request.user.is_authenticated):
        if(userAccount.objects.filter(user=request.user).count()>0):
            return HttpResponseRedirect(reverse('userAccount:view_account'))
        else:
            user = request.user
            new_account = userAccount(user=user, first_name=user.first_name, last_name=user.last_name)
            new_account.save()
            return HttpResponseRedirect(reverse('userAccount:view_account'))
    else:
        messages.add_message(request, messages.ERROR, "Login before attempting to view account")
        return HttpResponseRedirect(reverse('login:login'))

def view_account(request):
    if(request.user.is_authenticated):
        template = loader.get_template('userAccount/accountForm.html')
        currentUser = userAccount.objects.get(user=request.user)
        courses = currentUser.getCourses()

        courses_as_str = []
        for course in courses:
            courses_as_str.append(course.mnemonic + " " + course.number)

        context = {
            'acc_first_name' : currentUser.first_name,
            'acc_last_name' : currentUser.last_name,
            'acc_major' : currentUser.major,
            'acc_bio' : currentUser.bio,
            'email' : currentUser.user.email,
            'courses' : ','.join(courses_as_str),
            'major_options' : major_options,
            'course_data' : course_data
        }
        return HttpResponse(template.render(context,request))
    else:
        messages.add_message(request, messages.ERROR, "Login before attempting to view account")
        return HttpResponseRedirect(reverse('login:login'))

def save(request):
    try:
        currentUser = userAccount.objects.get(user=request.user)
        acc_first_name = request.POST.get("acc_first_name")
        acc_last_name = request.POST.get("acc_last_name")
        acc_major = request.POST.get("acc_major")
        acc_bio = request.POST.get("acc_bio")
        currentUser.first_name = acc_first_name
        currentUser.last_name = acc_last_name
        currentUser.major = acc_major
        currentUser.bio = acc_bio
        currentUser.save()

        courses_to_add = request.POST.getlist("acc_courses_added[]")
        courses_to_remove = request.POST.getlist("acc_courses_removed[]")
        all_courses = Course.objects.filter(student=currentUser)

        for delete_course in courses_to_remove:
            for course in all_courses:
                if course.mnemonic == delete_course.split(" ")[0] and course.number == delete_course.split(" ")[1]:
                    course.delete()
        
        for add_course in courses_to_add:

            # Will quietly ignore any duplicate courses
            is_duplicate = False
            for course in all_courses:
                if course.mnemonic == add_course.split(" ")[0] and course.number == add_course.split(" ")[1]:
                    is_duplicate = True

            if not is_duplicate:
                new_course = Course(student=currentUser, mnemonic=add_course.split(" ")[0], number=add_course.split(" ")[1])
                new_course.save()

        messages.add_message(request, messages.SUCCESS, "Account information successfully updated")
        return HttpResponseRedirect(reverse('userAccount:contact_info'))
    except:
        if(request.user.is_authenticated):
            messages.add_message(request, messages.ERROR, "Error updating account information")
            return HttpResponseRedirect(reverse('userAccount:view_account'))
        else:
            messages.add_message(request, messages.ERROR, "Login before attempting to view account")
            return HttpResponseRedirect(reverse('login:login'))


def view_buddies(request):
    if(request.user.is_authenticated):
        if (userAccount.objects.filter(user=request.user).count() > 0):
            currentUser = userAccount.objects.get(user=request.user)
        else:
            return HttpResponseRedirect(reverse('login:home'))

        template = loader.get_template('userAccount/buddies.html')
        buddies = currentUser.getBuddies()

        buddies_with_notifications = []
        buddy_num_notifications = {}

        for buddy in buddies["accepted"]:
            num_unread = get_num_unread(buddy, request.user)
            if num_unread != 0:
                buddies_with_notifications.append(buddy.user)
                buddy_num_notifications[buddy.user] = num_unread

        for buddy in buddies["pendingYourApproval"]:
            num_unread = get_num_unread(buddy, request.user)
            if num_unread != 0:
                buddies_with_notifications.append(buddy.user)
                buddy_num_notifications[buddy.user] = num_unread

        for buddy in buddies["pendingTheirApproval"]:
            num_unread = get_num_unread(buddy, request.user)
            if num_unread != 0:
                buddies_with_notifications.append(buddy.user)
                buddy_num_notifications[buddy.user] = num_unread

        context = {
            'acc_name' : currentUser.first_name + ' ' +currentUser.last_name,
            'accepted_buddies' : buddies["accepted"],
            'pending_your_approval' : buddies["pendingYourApproval"],
            'pending_their_approval' : buddies["pendingTheirApproval"],
            'selected_buddy' : None,
            'buddies_with_notifications': buddies_with_notifications,
            'buddy_num_notifications': buddy_num_notifications
        }
        return HttpResponse(template.render(context,request))
    else:
        messages.add_message(request, messages.ERROR, "Login before attempting to view buddies")
        return HttpResponseRedirect(reverse('login:login'))

def buddy_select(request, buddy_name):
    if(request.user.is_authenticated):
        buddy = User.objects.get(username=buddy_name)
        buddy_account = userAccount.objects.get(user=buddy)
        study_buddy_list_length = len(buddy_account.getBuddies()["accepted"])
        template = loader.get_template('userAccount/buddies.html')
        currentUser = userAccount.objects.get(user=request.user)
        buddies = currentUser.getBuddies()
        shared_courses = currentUser.getSharedCourses(buddy_account)

        # Availability
        days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
        times = []
        for i in range(8, 12):
            times.append(str(i) + ":00 AM")
        times.append("12:00 PM")
        for i in range(1,12):
            times.append(str(i) + ":00 PM")

        user_availability = Availability.objects.get(student=currentUser).calendar
        buddy_availability = Availability.objects.get(student=buddy_account).calendar

        form = MyForm()

userAccount/templates/userAccount/accountForm.html
{% extends "login/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'userAccount/profile.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>

  let isLoaded = false;

  let courses = "{{ courses }}".split(",").filter(s => s !== '');
  let courseDataEncoded = "{{ course_data }}";
  let courseData;
  let selectedCourseMnemonic = "";
  let selectedCourseNumber = "";
  let coursesAdded = [];
  let coursesRemoved = [];
  let isSaved;

  const coursesChipHead = '<div class="course-chip">';
  const coursesChipMid = "<img class=\"x-icon\" src=\"{% static 'userAccount/images/clear-24px.svg' %}\" onclick=\"removeCourse('"
  const coursesChipTail = "')\"></div>";

  window.addEventListener('load', function() {
    isLoaded = true;
    displayCourses();

    selectedCourseMnemonic = "AAS";
    selectedCourseNumber = "1010";
    selectedCourseApplyStyles();
    setIsSaved(true);

    courseData = decodeCourseData(courseDataEncoded);
    displaySelectableCourses();

    const majorSelect = document.getElementById('acc_major');
    const courseMnemonicSelect = document.getElementById('selected-course-mnemonic');
    const courseDescSelect = document.getElementById("selected-course-desc");
    const accountForm = document.getElementById("account_form");
    majorSelect.value = "{{ acc_major }}";
    courseDescSelect.value = "1010 - African-Amer & African Stds I";

    courseMnemonicSelect.addEventListener('change', function() {
      selectedCourseMnemonic = courseMnemonicSelect.value;
      displaySelectableCourses();
      selectedCourseApplyStyles();
    });

    courseDescSelect.addEventListener('change', function() {
      selectedCourseNumber = courseDescSelect.value.slice(0, 4);
      selectedCourseApplyStyles();
    });

    accountForm.addEventListener('change', function() {
      setIsSaved(false);
    });

    toastr.options = {
      "positionClass": "toast-bottom-right",
      "timeOut": "2000",
    }
  });

  // Reload if page is loaded from bfcache
  window.onpageshow = function(event) {
    if (event.persisted && isLoaded) {
        window.location.reload() 
    }
  };

  function setIsSaved(saved) {
    isSaved = saved;
    document.getElementById("save-button").disabled = isSaved;
  }

  function decodeCourseData(data) {
    return JSON.parse(data.replaceAll("&#x27;", "\""));
  }

  function displaySelectableCourses() {
    let s = '';
    for (let i in courseData[selectedCourseMnemonic]) {
      s += '<option value="' + courseData[selectedCourseMnemonic][i] + '">' + courseData[selectedCourseMnemonic][i] + '</option>';
    }
    document.getElementById('selected-course-desc').innerHTML = s;
    selectedCourseNumber = document.getElementById("selected-course-desc").value.slice(0,4);
  }

  function displayCourses() {
    let s = '';
    for (let course in courses) {
      s += coursesChipHead + courses[course] + coursesChipMid + courses[course] + coursesChipTail;
    }
    document.getElementById('courses-display').innerHTML = s;
  }

  function removeCourse(course) {
    courses = courses.filter((item) => item != course);
    if (coursesAdded.includes(course)) {
        coursesAdded = coursesAdded.filter((item) => item != course);
    } else {
      coursesRemoved.push(course);
    }
    setIsSaved(false);
    displayCourses();
    selectedCourseApplyStyles();
  }

  function addCourse() {
    document.getElementById("courses-dispaly-container").classList.remove("courses-display-error");
    document.getElementById("courses-error-message").classList.remove("show-error");

    let course = selectedCourseMnemonic;
    course += ' ' + selectedCourseNumber;
    if (!courses.includes(course)) {
      if (coursesRemoved.includes(course)) {
        coursesRemoved = coursesRemoved.filter((item) => item != course);
      } else {
        coursesAdded.push(course);
      }
      courses.push(course);
      displayCourses();
      setIsSaved(false);
    }
    selectedCourseApplyStyles();
  }

  function selectedCourseApplyStyles() {
    const iconElement = document.getElementById('add-icon');
    if (courses.includes(selectedCourseMnemonic + ' ' + selectedCourseNumber)) {
      iconElement.classList.add("add-icon-disabled");
    } else {
      iconElement.classList.remove("add-icon-disabled");
    }
  }

  function onContinue(link) {
    if (!isSaved) {
      swal({
        title: "Are you sure you want to leave?",
        text: "Your unsaved changes will be lost.",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      })
      .then((value) => {
        if (value) {
          document.getElementById(link).click();
        }
      });
    } else {
      document.getElementById(link).click();
    }
  }

  function save(continueLink) {
    let isValid = true;

    const accountForm = document.getElementById("account_form");
    if (accountForm.checkValidity() === false) {
      accountForm.classList.add('was-validated');
      isValid = false;
    }
    if (courses.length === 0) {
      document.getElementById("courses-dispaly-container").classList.add("courses-display-error");
      document.getElementById("courses-error-message").classList.add("show-error");
      isValid = false;
    }

    if (!isValid) return;

    const body = {
      "acc_first_name": document.getElementById("acc_first_name").value,
      "acc_last_name": document.getElementById("acc_last_name").value,
      "acc_major": document.getElementById("acc_major").value,
      "acc_bio": document.getElementById("acc_bio").value,
      "acc_courses_added": coursesAdded,
      "acc_courses_removed": coursesRemoved,
      'csrfmiddlewaretoken': '{{ csrf_token }}'
    }
    $.post("{% url 'userAccount:save' %}", body, function(data, status) {
      if (continueLink && status === "success") {
        setIsSaved(true);
        onContinue(continueLink);
      } else if (status === "success") {
        toastr.success("Profile updated");
        setIsSaved(true);
        accountForm.classList.remove('was-validated');
      } else {
        toastr.error("An error occurred. Profile could not be updated.");
      }
    });
  }

</script>

<div class="root-container">
  <div class="form-header">
    <div class="stepper">
      <div class="stepper-container">
          <div class="stepper-node selected"><span class="stepper-node-text">1</span></div>
          <span class="stepper-text selected-text">Profile</span>
      </div>
      <div class="stepper-separator"></div>
      <div class="stepper-container" onclick="onContinue('hidden-link')">
          <div class="stepper-node"><span class="stepper-node-text">2</span></div>
          <span class="stepper-text">Contact Info</span>
      </div>
      <div class="stepper-separator"></div>
      <div class="stepper-container" onclick="onContinue('hidden-link-avail')">
          <div class="stepper-node"><span class="stepper-node-text">3</span> </div>
          <span class="stepper-text">Availability</span>
      </div>
  </div>
  </div>
  <div class="form-body">
    <div class="form-body-left">
    <form
      action="{% url 'userAccount:save' %}"
      id="account_form"
      method="post"
      class="needs-validation"
      novalidate
      >
      {% csrf_token %}
      <div class="form-group row">
        <label for="acc_first_name" class="col-sm-3 col-form-label">First Name<span>&nbsp;*</span></label>
        <div class="col-sm-9">
          <input type="text" class="form-control" id="acc_first_name" value="{{ acc_first_name }}" name = "acc_first_name" required>
          <div class="invalid-feedback">
            First name is required.
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="acc_last_name" class="col-sm-3 col-form-label">Last Name<span>&nbsp;*</span></label>
        <div class="col-sm-9">
          <input type="text" class="form-control" id="acc_last_name" value="{{ acc_last_name }}" name = "acc_last_name" required>
          <div class="invalid-feedback">
            Last name is required.
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="acc_major" class="col-sm-3 col-form-label">Major<span>&nbsp;*</span></label>
        <div class="col-sm-9">
          <select
            id="acc_major"
            class="form-control"
            required
            >
            <option value=""></option>
            {% for major in major_options %}
              <option value="{{ major }}">{{ major }}</option>
            {% endfor %}
          </select>
          <div class="invalid-feedback">
            Major is required.
          </div>
        </div>
      </div>
      <div class="form-group row form-textarea">
        <label for="acc_bio" class="col-sm-3 col-form-label">Bio<span>&nbsp;*</span></label>
        <div class="col-sm-9">
          <textarea
            class="form-control bio-textarea"
            id="acc_bio"
            name = "acc_bio"
            placeholder="Tell us a bit about yourself. Where do you need the most help? What can you help others with?"
            required
            >{{ acc_bio }}</textarea>
          <div class="invalid-feedback">
            Bio is required.
          </div>
        </div>
      </div>
    </form>
    </div>
    <div class="form-body-right">
      <div class="courses-header">
        <span class="courses-header-text">Courses</span>
      </div>
      <div class="courses-select-form-container">
        <form class="courses-select-form">
          <div class="form-row courses-select-row">
            <div class="col-xl-3 col-lg-4">
              <select
                id="selected-course-mnemonic"
                class="form-control"
                >
                {% for mnemonic in course_data.keys %}
                  <option value="{{ mnemonic }}">{{ mnemonic }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-xl-8 col-lg-7">
              <select
                id="selected-course-desc"
                class="form-control"
                >
              </select>
            </div>
            <div class="col col-sm-1 add-icon-container">
              <img onclick="addCourse()" id="add-icon" class="add-icon" src="{% static 'userAccount/images/add_circle-24px.svg' %}">
            </div>
          </div>
        </form>
      </div>
      <div id="courses-dispaly-container" class="courses-dispaly-container">
        <div id="courses-display" class="courses-display">
          <!-- Will be filled by displayCourses() -->
        </div>
      </div>
      <div id="courses-error-message" class="courses-error-message">
        <span>You must add at least one course.</span>
      </div>
    </div>
  </div>
  <div class="form-footer">
    <button
      id="save-button"
      class="btn btn-success save-button"
      onclick="save()"
      >
      Save
    </button>
    <a
      onclick="save('hidden-link')"
    >
      <button
        class="btn btn-outline-primary"
        >
        Save and Continue
      </button>
    </a>
    <a id="hidden-link-avail" href="{% url 'userAccount:has_availability' %}" style="display: none;"></a>
    <a id="hidden-link" href="{% url 'userAccount:contact_info' %}" style="display: none;"></a>
  </div>
</div>
{% endblock %}

userAccount/templates/userAccount/classForm.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Add a Class</title>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="jumbotron">
      <h1>Add a Class</h1>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    

      <div class="container">

        <h2>Add a class below</h2>
        <form action="{% url 'userAccount:add_class' %}" id = "class_form" method="post">
            {% csrf_token %}
          <div class="form-group">
            <label for="course_mnemonic">course mnemonic</label>
            <input type="text" class="form-control" id="course_mnemonic" placeholder="MATH" name = "course_mnemonic">
            <label for="course_number">course number</label>
            <input type="text" class="form-control" id="course_number" placeholder="1010" name = "course_number">
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
        </form>
      </div>
  </body>
</html>